blank_issues_enabled: false
contact_links:
  - name: Sponsor this Project
    url: https://gist.github.com/juancarlospaco/37da34ed13a609663f55f4466c4dbc3e
    about: |
      :heart: Send crypto today to speed up development!.
      Toss a coin to your witcher...
