name: Build
on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy3"]
        architecture: ["x64", "x86"]
    name: ${{ matrix.platform }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      uses: allenevans/set-env@v2.0.0
      with:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: "stable"

    - name: Nimble
      run: |
        nimble -y refresh
        nimble -y install nimpy

    - uses: pre-commit/action@v2.0.3
      if: runner.os == 'Linux'
