name: Build
on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        architecture: ["x64", "x86"]
    name: ${{ matrix.platform }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      uses: allenevans/set-env@v2.0.0
      with:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        CMD: "nim doc -d:nimStrictDelete -d:nimPreviewFloatRoundtrip -d:nimPreviewDotLikeOps --gc:orc --index:on --project --experimental:strictEffects --experimental:strictFuncs --styleCheck:usages --styleCheck:hint --outdir:../../docs"

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # - uses: pre-commit/action@v2.0.3
    #   if: runner.os == 'Linux'

    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: "stable"

    - name: Nimble setup
      run: |
        nimble -y refresh
        nimble -y install nimpy

    - name: Build docs
      shell: bash
      run: |
        cd src/cpython/
        $CMD atexit
        $CMD base64
        $CMD binascii
        $CMD binhex
        $CMD builtins
        $CMD bz2
        $CMD cmath
        $CMD codecs
        $CMD codeop
        $CMD colorsys
        $CMD compileall
        $CMD copy
        $CMD crypt
        $CMD curses
        $CMD dbd
        $CMD decimal
        $CMD dis
        $CMD doctest
        $CMD ensurepip
        $CMD errno
        $CMD faulthandler
        $CMD fcntl
        $CMD filecmp
        $CMD fnmatch
        $CMD gc
        $CMD getopt
        $CMD getpass
        $CMD gettext
        $CMD glob
        $CMD grp
        $CMD gzip
        $CMD hashlib
        $CMD hmac
        $CMD html_entities
        $CMD imghdr
        $CMD imp
        $CMD importlib
        $CMD keyword
        $CMD linecache
        $CMD logging
        $CMD lzma
        $CMD marshal
        $CMD math
        $CMD mimetypes
        $CMD nis
        $CMD ntpath
        $CMD operator
        $CMD os
        $CMD pickle
        $CMD pickletools
        $CMD pkgutil
        $CMD posixpath
        $CMD pprint
        $CMD pwd
        $CMD py_compile
        $CMD quopri
        $CMD random
        $CMD re
        $CMD readline
        $CMD reprlib
        $CMD resource
        $CMD runpy
        $CMD secrets
        $CMD shutil
        $CMD signal
        $CMD site
        $CMD sndhdr
        $CMD spwd
        $CMD ssl
        $CMD statistics
        $CMD struct
        $CMD subprocess
        $CMD sys
        $CMD sysconfig
        $CMD syslog
        $CMD tabnanny
        $CMD tempfile
        $CMD termios
        $CMD textwrap
        $CMD timeit
        $CMD token
        $CMD tty
        $CMD turtle
        $CMD typing
        $CMD unicodedata
        $CMD uu
        $CMD uuid
        $CMD venv
        $CMD warnings
        $CMD webbrowser
        $CMD winsound
        $CMD zipapp
        $CMD zlib

    - name: Clean out
      shell: bash
      run: |
        rm --verbose --force --recursive docs/*.idx
        rm --verbose --force --recursive docs/nimcache/*.*
        rm --verbose --force --recursive docs/nimcache/runnableExamples/*.*
