name: Build
on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        platform:       [ubuntu-latest, windows-latest]
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        nim-channel:    [stable, devel]
    name: ${{ matrix.platform }}-${{ matrix.python-version }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      uses: allenevans/set-env@v2.0.0
      with:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        CMD: "nim doc -d:nimStrictDelete -d:nimPreviewFloatRoundtrip -d:nimPreviewDotLikeOps --gc:orc --index:on --project --experimental:strictEffects --experimental:strictFuncs --styleCheck:usages --styleCheck:hint --outdir:../../docs"

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # - uses: pre-commit/action@v2.0.3
    #   if: runner.os == 'Linux'

    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Nimble setup
      run: |
        nimble -y refresh
        nimble -y install nimpy

    - name: Build docs
      shell: bash
      run: |
        cd src/cpython/
        for i in *.nim; do
          $CMD $i
        done

    - name: Build UPBGE docs
      shell: bash
      run: |
        cd src/cpython/upbge/
        for i in *.nim; do
          $CMD $i
        done

    - name: Clean out
      shell: bash
      run: |
        rm --verbose --force --recursive docs/*.idx
        rm --verbose --force --recursive docs/nimcache/*.*
        rm --verbose --force --recursive docs/nimcache/runnableExamples/*.*
