name: Wiki On Edit
on:   gollum  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#gollum
jobs:
  wiki_on_edit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add Wiki Editors to Wiki Changelog
      run: |
        echo -e "- <code>${{github.event.repository.updated_at}}</code>\t<kbd title='${{github.event.pages[0].sha}}'>SHA</kbd>\t<img src='${{github.event.sender.avatar_url}}' width=20 height=20 /> [@${{github.actor}}](https://github.com/${{github.actor}} '${{github.event.sender.login}}') ${{github.event.pages[0].action}} [${{github.event.pages[0].page_name}}](${{github.event.pages[0].html_url}} '${{github.event.pages[0].title}}') with message '${{github.event.pages[0].summary}}'." >> wiki_changelog.md

    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'nim'
