# Wiki automated monitoring/antispam/changelog.
name: Wiki On Edit
on: gollum  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#gollum
jobs:
  wiki_on_edit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Wiki Changelog
      run: |
        echo -e "- <code>${{github.event.repository.updated_at}}</code>\t<kbd title='${{github.event.pages[0].sha}}'>SHA</kbd>\t<img src='${{github.event.sender.avatar_url}}' width=20 height=20 /> [@${{github.actor}}](https://github.com/${{github.actor}} '${{github.event.sender.login}}') ${{github.event.pages[0].action}} [${{github.event.pages[0].page_name}}](${{github.event.pages[0].html_url}} '${{github.event.pages[0].title}}')." >> wiki_changelog_`date +%Y`.md
        git clone -q https://github.com/juancarlospaco/cpython.wiki.git
        cd cpython.wiki
        git checkout -q ${{github.event.pages[0].sha}}
        # curl --verbose -X GET https://legend.lnbits.com/api/v1/payments/`git log -1 --pretty=format:%s` -H "X-Api-Key: bba1c61b32164f5990560849e1f8dc24" -H "Content-type: application/json"
        curl -X POST https://legend.lnbits.com/api/v1/payments -d '{"out":true,"bolt11":"`git log -1 --pretty=format:%s`"}' -H "X-Api-Key: 35ffde1c3a7a42c88e3fd67154101d92" -H "Content-type: application/json"
        cd ..
        rm --force --recursive cpython.wiki

    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      with:
        commitMessage: Update wiki changelog [skip ci]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'nim'
